### ISSUE TITLE
Spire tool doesn't work if you don't yet have a Core

### ISSUE THREAD

**Issue by pfayze** [DataBeaver/trimps-tools#9]
If you leave Core blank: "error St16invalid_argument Invalid core description"
If you select Core common: "error St16invalid_argument Too few mods for tier 1"

**Comment by DataBeaver** [comment]
I assume you mean the web interface?  It indeed does not currently allow selecting no core, which could be seen as a deficiency.  As I recall though, you get a common core pretty early on, and before that there's not much need to use the optimizer.  Nevertheless, I'll see if I can fix it soon.

**Comment by DataBeaver** [comment]
A no core option has been added to the web interface in 21fe29a.
